language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - pip install nose

script: nosetests --with-coverage --cover-package=aliyunauth

after_success:
    - pip install coveralls
    - coveralls
